### ISSUE TITLE
Update for OpenFL 1.1

### ISSUE THREAD

**Issue by Slakinov** [hyperfiction/HypMedias#1]
Thanks for sharing this lib! Unfortunately there are some issues with OpenFL1.1 (dev branch).

Your macro @:build( ShortCuts.mirrors( ) ) barfs, what does that do?

import nme.\* needs to be updated to import flash.*

After commenting out the macro and updating the imports, xcode traced out the following when it should have been playing a video:
HypVideo: register_prims()

Any ideas what needs to be updated?

Thanks again for sharing!

**Comment by shoebox** [comment]
Hi !

My fault, i've forgot a dependency in the haxelib.

You need to install "inthebox-macros" and add it to your project.xml (Take a look at the demo)

For OpenFL it's a dev branch so not yet tested...

Have Fun //

For OpenFL it's a dev branch and it's untested on it for now.

**Comment by Slakinov** [comment]
Great, thanks for the info :]

**Comment by Slakinov** [comment]
Good news!
The extension works with OpenFL 1.1 once inthebox-macros is installed and those imports are changed to flash.events...

Any suggestions as to how I could add in some init options to hide the player controls?

**Comment by shoebox** [comment]
On which platform ?

**Comment by Slakinov** [comment]
Sorry... iOS 7

**Comment by shoebox** [comment]
Take a look at the MPMoviePlayerController class there is probably a property or a way to hiding them...
https://developer.apple.com/library/ios/documentation/mediaplayer/reference/MPMoviePlayerController_Class/Reference/Reference.html

**Comment by Slakinov** [comment]
Thanks again, we're looking to extend this to include options to hide controls and a button overlay to skip the whole video. Will make a fork if you're interested.

**Comment by shoebox** [comment]
A pull request would be cool.

Thanks !
